### ISSUE TITLE
解压密码

### ISSUE THREAD

**Issue by ghost** [ljw1006/Operating-System-2019#1]
课件和工具书都有密码，望助教告知

**Comment by ljw1006** [comment]
USTC1733,你能看到吗------------------ 原始邮件 ------------------
发件人: "clague"<notifications@github.com>
发送时间: 2019年9月6日(星期五) 下午2:27
收件人: "ljw1006/Operating-System-2019"<Operating-System-2019@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [ljw1006/Operating-System-2019] 解压密码 (#1)



课&#x4EF6;和工具书都有密码，望助教告知
 
&mdash;

**Comment by ghost** [comment]
> USTC1733,你能看到吗------------------ 原始邮件 ------------------ 发件人: "clague"<notifications@github.com> 发送时间: 2019年9月6日(星期五) 下午2:27 收件人: "ljw1006/Operating-System-2019"<Operating-System-2019@noreply.github.com>; 抄送: "Subscribed"<subscribed@noreply.github.com>; 主题: [ljw1006/Operating-System-2019] 解压密码 (#1) 课&#x4EF6;和工具书都有密码，望助教告知 &mdash; You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

解压码可用，十分感谢！
